# Generated by Django 4.0 on 2022-01-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SALARY', 'SALARY'), ('BUSINESS', 'BUSINESS'), ('FOOD', 'FOOD'), ('SIDE-HUSTLES', 'SIDE-HUSTLES'), ('OTHER', 'OTHER')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('description', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='authentication.user')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
